### ISSUE TITLE
Little Question

### ISSUE THREAD

**Issue by jgauchia** [pepijndevos/bicycle_gps#2]
Hello,
First of all, sorry for my English.
I am doing a personal project of a GPS navigator with an ESP32.
I am currently using raster (PNG) maps. I have seen your project to be able to vectorize maps from an OSM file.
It's great!
But I have a question, I have no knowledge of Rust...
How can I convert the OSM file to an R-tree file so that I can use it?
Thanks and sorry for the question.

**Comment by pepijndevos** [comment]
This project is a decade old and doesn't work with modern Rust.
You might have more luck with my more recent project https://github.com/pepijndevos/mapseflaps

**Comment by jgauchia** [comment]
Thank you!
I'll take a look.
